name: Deploy Static Website to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug Host
        run: echo "Deploying to ${{ secrets.USER }}@${{ secrets.HOST }}"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} 2>/dev/null >> ~/.ssh/known_hosts

      - name: Deploy static files to EC2
        run: |
          rsync -avz --delete \
            --exclude=".git*" \
            ./ \
            ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/html/
